### ISSUE TITLE
Сделать отдельный микросервис для парсинга аудиособщений из очереди

### ISSUE THREAD

**Issue by yuloskov** [yuloskov/speech-notes#2]

**Comment by vstpme** [comment]
Я немного на бэке там написал, @Dantara можешь эндпоинт сделать такой: принимает файл `audio_file` и ссылку куда вернуть текст `callback_url`. Когда все распаршено и готово, нужно отправить на `callback_url` `POST` запрос с пейлоадом в формате `{success: true|false, text: "some text"}`.

Т.е. example request входящий в STT сервис:
```
{
    "audio_file": File,
    "callback_url": "http://some-site.xyz/notes/21/process_audio_callback/"
}
```

Example request to `callback_url`:
```
{
    "success": true,
    "text": "sample text"
}
```

**Comment by Dantara** [comment]
@vadimkerr, вопрос по request'у входящему в STT. Я так понимаю, ты предлагаешь тело запроса сделать `json`'ном. Но если так, то как ты предлагаешь вставить медиа файл внутрь `json`? Я на данный момент вижу три варианта:
1) Перекодировать файл в `base64` и отправлять текстом. При этом подходе есть пара проблем: с кодировкой / декодировкой и у нас появляется дополнительный overhead (при кодировании и декодировании).
2) Сохранять файлы у тебя и отправлять лишь ссылки, чтобы микросервис сам их скачивал. После получения callback'a ты файлы удаляешь.
3) Использовать `multipart/form-data` в качестве тела запроса. Он позволяет отправлять файлы, а так же пары типа ключ-значение.
На мой взгляд, последний вариант выглядит самым оптимальным)

**Comment by vstpme** [comment]
Да, 3
